name: OpenAPI Generator
'on':
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: 0 1 * * *
  workflow_dispatch: null
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate OpenAPI Generator Client
        uses: openapi-generators/openapitools-generator-action@v1.3.0
        with:
          generator: java
          openapi-file: finicity.yaml
          generator-tag: latest-release
      - uses: actions/upload-artifact@v3
        with:
          name: generated-client
          path: java-client/
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: adopt
      - name: Build OpenAPI Generator Client
        run: |
          cd java-client
          mvn clean test
