# https://github.com/marketplace/actions/generate-client-library-w-the-openapitools-generator
name: OpenAPI Generator
'on':
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: 0 1 * * *
  workflow_dispatch: null
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Generate OpenAPI Generator Client
        uses: openapi-generators/openapitools-generator-action@v1.2.0
        with:
          generator: java
          openapi-file: finicity.yaml
