name: OpenAPI Generator
'on':
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: 0 1 * * *
  workflow_dispatch: null
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Generate OpenAPI Generator Client
        uses: openapi-generators/openapitools-generator-action@v1.2.0
        with:
          generator: java
          openapi-file: finicity.yaml
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: adopt
      - name: Build OpenAPI Generator Client
        run: |
          cd java-client
          mvn clean test