name: Swagger Editor

'on':

  push:

    branches:

      - '**'

  pull_request:

    branches:

      - '**'

  schedule:

    - cron: 0 1 * * *

  workflow_dispatch: null

jobs:

  validate:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout

        uses: actions/checkout@v3

      - name: Validate OpenAPI definition

        uses: char0n/swagger-editor-validate@v1.4.2

        with:

          definition-file: openbanking-us.yaml
