# https://github.com/marketplace/actions/swagger-editor-validator
name: Swagger Editor
'on':
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: 0 1 * * *
  workflow_dispatch: null
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate OpenAPI definition
        uses: char0n/swagger-editor-validate@v1.3.1
        with:
          definition-file: finicity.yaml
